name: mongo_dart
version: 0.5.1+1
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!
homepage: https://github.com/mongo-dart/mongo_dart
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  bson: ^0.3.4
  crypto: ^3.0.0
  logging: ^1.0.0
  mongo_dart_query: ^0.4.1
  collection: ^1.15.0
  path: ^1.7.0
  pool: ^1.4.0
  basic_utils: ^3.0.0
  rational: ^0.3.8
dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
  uuid: ^3.0.0

